import type { CategoryMeta } from "@/types";

/** Theme keys used to overlay SEO categories on the physical library. */
export const THEMES = [
  "nature",
  "cinematic",
  "fantasy",
  "scifi",
  "anime",
  "shorts",
] as const;

export type Theme = (typeof THEMES)[number];

export interface CategoryDef {
  slug: string;
  name: string;
  icon: string;
  title: string;
  description: string;
  seoContent: string;
  /** how videos are selected for this page */
  kind: "all" | "theme" | "sort" | "folder";
  theme?: Theme;
  sort?: "trending" | "latest" | "popular" | "downloads";
  downloadUrl?: string;
}

/**
 * SEO landing categories. These power /[category] routes, the nav,
 * and the homepage sections.
 */
export const CATEGORIES: CategoryDef[] = [
  {
    slug: "free-ai-videos",
    name: "Free AI Videos",
    icon: "Sparkles",
    kind: "all",
    title: "Free AI Video Download | No Watermark AI Generated Videos",
    description: "Download premium AI generated videos for free. No watermark, no sign-up. High-quality AI clips updated daily.",
    seoContent: "Explore our complete library of free AI generated videos. Every clip is rendered in high definition and free to download with no watermark.",
  },
  {
    slug: "trending-ai-videos",
    name: "Trending AI Videos",
    icon: "Flame",
    kind: "sort",
    sort: "trending",
    title: "Trending AI Videos | Viral & Most Popular AI Clips Right Now",
    description: "See the trending AI videos everyone is downloading right now. The hottest AI generated clips.",
    seoContent: "These are the trending AI videos with the most momentum right now, ranked by a blend of views and downloads.",
  },
  {
    slug: "latest-ai-videos",
    name: "Latest AI Videos",
    icon: "Clock",
    kind: "sort",
    sort: "latest",
    title: "Latest AI Videos | New AI Generated Clips Added Daily (Free)",
    description: "Browse the latest AI generated videos added to our library. Fresh AI clips uploaded daily.",
    seoContent: "Stay ahead with the latest AI videos added to our gallery. We publish new AI generated clips every day.",
  },
  {
    slug: "popular-ai-videos",
    name: "Popular AI Videos",
    icon: "Star",
    kind: "sort",
    sort: "popular",
    title: "Popular AI Videos | Most Viewed AI Generated Videos (Top 100)",
    description: "The most popular AI videos of all time, ranked by total views. Download the viral AI clips.",
    seoContent: "Our most popular AI videos of all time, ranked by total views. These crowd favorites have been watched and downloaded thousands of times.",
  },
  {
    slug: "ai-animal-videos",
    name: "AI Animal Videos",
    icon: "Cat",
    kind: "folder",
    title: "Free AI Animal Videos | HD AI Generated Wildlife",
    description: "Download high-quality AI generated animal videos for free. No watermark.",
    seoContent: "Explore our exclusive collection of AI animal videos featuring stunning AI-generated wildlife.",
    downloadUrl: "/bundles/ai-animal-videos.pdf",
  },
  {
    slug: "ai-miniature-reels",
    name: "AI Miniature Reels",
    icon: "Castle",
    kind: "folder",
    title: "Free AI Miniature Reels | Tiny Worlds AI Generated",
    description: "Download high-quality AI generated miniature reels. Free miniature worlds in HD.",
    seoContent: "Discover our miniature reels collection with AI-generated tiny landscapes and objects.",
    downloadUrl: "https://drive.google.com/drive/folders/1r6mz7_zRJV5Q2Yh5dUk8XykYPJixoIIh?usp=sharing",
  },
  {
    slug: "ai-tech-reels",
    name: "AI Tech Reels",
    icon: "Laptop",
    kind: "folder",
    title: "Free AI Tech Reels | Futuristic Tech AI Videos",
    description: "Download futuristic AI generated tech reels and clips in HD.",
    seoContent: "A huge collection of AI generated tech reels perfect for modern creators.",
    downloadUrl: "https://drive.google.com/drive/folders/1owz3KRZ3QJaB2TdwxWuj0IAhjJ2b7mzy?usp=sharing",
  },
  {
    slug: "car-reels",
    name: "Car Reels",
    icon: "Car",
    kind: "folder",
    title: "Free Car Reels | High-End Car Edits",
    description: "Download amazing AI generated car reels and sports car edits.",
    seoContent: "Check out our car reels category for the most epic automotive AI clips.",
    downloadUrl: "https://drive.google.com/drive/folders/1_HJ-_6HQPntHiS324eaBbjQ4ZcPTnyoo?usp=sharing",
  },
  {
    slug: "funny-fails-clips",
    name: "Funny Fails Clips",
    icon: "Laugh",
    kind: "folder",
    title: "Free Funny Fails Clips | Hilarious AI Fails",
    description: "Download the funniest AI generated fails and comedy clips.",
    seoContent: "Get ready to laugh with our funny fails clips collection entirely generated by AI.",
    downloadUrl: "https://drive.google.com/drive/folders/1Fpdfc8UTZWjhS0nsNbrCOTjSmq2gu_qP?usp=sharing",
  },
  {
    slug: "luxury-reels-bundle",
    name: "Luxury Reels Bundle",
    icon: "Gem",
    kind: "folder",
    title: "Free Luxury Reels Bundle | Premium Lifestyle Edits",
    description: "Download luxury AI reels bundle for lifestyle motivation videos.",
    seoContent: "Elevate your content with our luxury reels bundle featuring premium lifestyle clips.",
    downloadUrl: "https://drive.google.com/drive/folders/1lZCisZagEQ-manu_Gq-UKXRibWxxZYE2?usp=sharing",
  },
  {
    slug: "satisfying-reels",
    name: "Satisfying Reels",
    icon: "Droplet",
    kind: "folder",
    title: "Free Satisfying Reels | Oddly Satisfying AI Videos",
    description: "Download oddly satisfying AI generated reels in 4K/HD.",
    seoContent: "Find peace and engagement with our oddly satisfying reels category.",
    downloadUrl: "https://drive.google.com/drive/folders/1Nok4R2QDeR4W4PDaW69-ev5bGWOjSD2j?usp=sharing",
  },
  {
    slug: "study-reels",
    name: "Study Reels",
    icon: "BookOpen",
    kind: "folder",
    title: "Free Study Reels | Lofi Study & Focus Videos",
    description: "Download study motivation and lofi aesthetic AI videos.",
    seoContent: "Perfect background clips for your study or lofi channels in our study reels collection.",
    downloadUrl: "https://drive.google.com/drive/folders/1YB0JP-KKxWNP9yoNTEQHDOkScsqB1Lvt?usp=sharing",
  },
  {
    slug: "super-hero-videos",
    name: "Super Hero Videos",
    icon: "Shield",
    kind: "folder",
    title: "Free Super Hero Videos | Epic AI Heroes",
    description: "Download epic AI generated super hero videos in HD.",
    seoContent: "Action-packed super hero videos generated by AI for free download.",
    downloadUrl: "https://drive.google.com/drive/folders/1iIQmsdtwAjwq59ZPOT05oDSoI609wGXt?usp=sharing",
  },
  {
    slug: "tools-tips-reels",
    name: "Tools Tips Reels",
    icon: "Wrench",
    kind: "folder",
    title: "Free Tools & Tips Reels | AI Life Hacks",
    description: "Download helpful AI generated tools and tips reels.",
    seoContent: "Educational and informative tools and tips reels created by AI.",
    downloadUrl: "https://drive.google.com/drive/folders/1XYlRDzGbH9H_xfnlSicdGlpoQDhR1I1d?usp=sharing",
  },
  {
    slug: "emotional",
    name: "Emotional",
    icon: "Heart",
    kind: "folder",
    title: "Free Emotional Videos | Touching AI Clips",
    description: "Download deeply emotional and touching AI generated videos.",
    seoContent: "A curated collection of emotional AI videos that resonate and inspire.",
    downloadUrl: "https://drive.google.com/drive/folders/1diFapWQooXFNjbrR4qZivB6mPBHJ5ISR?usp=sharing",
  },
  {
    slug: "nature",
    name: "Nature",
    icon: "Leaf",
    kind: "folder",
    title: "Free Nature Videos | AI Landscapes",
    description: "Download breathtaking AI generated nature videos and landscapes.",
    seoContent: "Stunning natural environments and scenery generated by AI.",
    downloadUrl: "https://drive.google.com/drive/folders/1wKIQKuU8eVHGORldwL2L_I-X3TIAkKg1?usp=sharing",
  }
];

export const CATEGORY_MAP: Record<string, CategoryDef> = Object.fromEntries(
  CATEGORIES.map((c) => [c.slug, c]),
);

/** Categories shown in the main navigation / chips. */
export const NAV_CATEGORIES = CATEGORIES.filter(
  (c) => c.kind === "folder" || c.slug === "trending-ai-videos" || c.slug === "free-ai-videos"
);

export function getCategory(slug: string): CategoryDef | undefined {
  return CATEGORY_MAP[slug];
}

export function toCategoryMeta(def: CategoryDef, count: number): CategoryMeta {
  return {
    slug: def.slug,
    name: def.name,
    folder: def.theme ?? def.slug,
    title: def.title,
    description: def.description,
    seoContent: def.seoContent,
    icon: def.icon,
    count,
  };
}
